### PR TITLE
🎯 Add .NET Standard targeting

### PR DESCRIPTION
**Pull request by tomrijnbeek**
One caveat: until we update to OpenTK 4.0.0 (which includes .NET Standard support), this won't be truly cross-platform. Once we do though... 😏

### CODE REVIEW

**Comment by tomrijnbeek** [comment]
Ready for review.

**Comment by tomrijnbeek** [comment]
Mostly because it's quite an interface breaking change. That being said,
it's not the first one we would break. If you want me to delete the code, I
will.

**Comment by amulware** [comment]
I would like you to remove it yeah. We don't really care about breaking changes that much.

**Comment by tomrijnbeek** [comment]
Oh, I know why I didn't delete it. Because in the .NET Framework it isn't included before .NET 4.8, and we support as low as .NET 4.6 right now. I don't even have .NET 4.8 installed, so I am not sure if we want to make this change.

**Pull request merged**
